summarizer:
    class: SomSummarizer

somz:
    n_r: 1
    n_m: 1
    randomize_selection: true
    randomize_noise: false


norm:
    # These estimates of the 10-sigma depths are used to
    # compute the "Luptitudes" from the magnitudes
    depths:
        g: 23.5
        i: 22.2
        r: 22.9
        u: 23.7
        y: 25.0
        z: 25.0
    # These Luptitude limits are used to normalize values
    # They don't have to be exact, just to roughly put most
    # values around 0 .. 1
    mag_min: 22
    mag_max: 28


redshift:
    input:
        format: hdf5
        file: ./spectroscopic_data.hdf5
        # This refers to an HDF5 group. For the root of the file,
        # use "/"
        group: /
        bands: riz
        # The format of the column names
        band_name: mag_{}

        # cut down the data for testing to this size
        nmax: 100000

        # If this is set the mag errors are also loaded
        load_errors: false
        error_name: mag_{}_err

        # A luptitude (if any) to include in the SOM
        # Omit or set to null for none
        use_band: i

        # Whether to load all the data at once (stream=false) or in chunks (stream=true)
        stream: false
        extra:
            redshift: redshift
    som:
        dim: 32
        epochs: 100
        rate: 0.5
        sigma: 1.0
        use_errors: false

    dz: 0.02
    zmax: 3.0

wide:
    input:
        format: hdf5
        file: ./wide_catalog.hdf5
        group: shear
        bands: riz
        band_name: mcal_mag_{}
        use_band: i
        load_errors: false
        # nmax: 1000000
        stream: true
        max_chunk_size: 200000
        random_chunk_order: true
        order_seed: 23456
    som:
        dim: 32
        epochs: 10
        rate: 0.5
        sigma: 1.0


output:
    deep_som: ./deep.som
    deep_name: ./deep_som
    zmaps: zmap.pkl

